services:
  mongo:
    container_name: scrape
    restart: always
    image: mongo:latest
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db 
    networks:
      - mongo-net
  scraper:
    container_name: scrape-bot
    restart: always
    image: 7uu13/scraper-bot:v1.0.3
    environment:
      BOT_TOKEN: 
      CHANNEL_ID:
      MONGO_URI: mongodb://mongo:27017/urls
    depends_on:
      - mongo
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge

volumes:
  dbdata: